<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="khadija" failures="1" tests="5" name="Sanity Test" time="0.068" errors="0" timestamp="2023-05-05T09:08:09 IST">
  <testcase classname="testng.TestNG_Example" name="my_log" time="0.005"/>
  <testcase classname="testng.TestNG_Example" name="my_login" time="0.001"/>
  <testcase classname="testng.TestNG_Example" name="test" time="0.001"/>
  <testcase classname="testng.TestNG_Example" name="test1" time="0.013">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at testng.TestNG_Example.test1(TestNG_Example.java:28)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase classname="testng.TestNG_Example" name="test3" time="0.003">
    <skipped/>
  </testcase> <!-- test3 -->
</testsuite> <!-- Sanity Test -->
