<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="khadija" failures="1" tests="2" name="Sanity Test(failed)" time="0.063" errors="0" timestamp="2023-05-05T09:09:39 IST">
  <testcase classname="testng.TestNG_Example" name="test1" time="0.019">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at testng.TestNG_Example.test1(TestNG_Example.java:28)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase classname="testng.TestNG_Example" name="test3" time="0.001">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase classname="testng.TestNG_Example" name="test" time="0.0">
    <ignored/>
  </testcase> <!-- test -->
  <testcase classname="testng.TestNG_Example" name="my_log" time="0.0">
    <ignored/>
  </testcase> <!-- my_log -->
  <testcase classname="testng.TestNG_Example" name="my_login" time="0.0">
    <ignored/>
  </testcase> <!-- my_login -->
</testsuite> <!-- Sanity Test(failed) -->
